// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonResp.proto

package com.doteyplay.game.message.proto;

public final class CommonRespProBuf {
  private CommonRespProBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PCommonRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 resultType = 1;
    /**
     * <code>required int32 resultType = 1;</code>
     *
     * <pre>
     *结果类型
     * </pre>
     */
    boolean hasResultType();
    /**
     * <code>required int32 resultType = 1;</code>
     *
     * <pre>
     *结果类型
     * </pre>
     */
    int getResultType();

    // required int32 status = 2;
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *请求状态0成功其他是失败
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *请求状态0成功其他是失败
     * </pre>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code PCommonResp}
   */
  public static final class PCommonResp extends
      com.google.protobuf.GeneratedMessage
      implements PCommonRespOrBuilder {
    // Use PCommonResp.newBuilder() to construct.
    private PCommonResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PCommonResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PCommonResp defaultInstance;
    public static PCommonResp getDefaultInstance() {
      return defaultInstance;
    }

    public PCommonResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PCommonResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doteyplay.game.message.proto.CommonRespProBuf.internal_static_PCommonResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doteyplay.game.message.proto.CommonRespProBuf.internal_static_PCommonResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.class, com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.Builder.class);
    }

    public static com.google.protobuf.Parser<PCommonResp> PARSER =
        new com.google.protobuf.AbstractParser<PCommonResp>() {
      public PCommonResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PCommonResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PCommonResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 resultType = 1;
    public static final int RESULTTYPE_FIELD_NUMBER = 1;
    private int resultType_;
    /**
     * <code>required int32 resultType = 1;</code>
     *
     * <pre>
     *结果类型
     * </pre>
     */
    public boolean hasResultType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 resultType = 1;</code>
     *
     * <pre>
     *结果类型
     * </pre>
     */
    public int getResultType() {
      return resultType_;
    }

    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *请求状态0成功其他是失败
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *请求状态0成功其他是失败
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      resultType_ = 0;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PCommonResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doteyplay.game.message.proto.CommonRespProBuf.PCommonRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doteyplay.game.message.proto.CommonRespProBuf.internal_static_PCommonResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doteyplay.game.message.proto.CommonRespProBuf.internal_static_PCommonResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.class, com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.Builder.class);
      }

      // Construct using com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doteyplay.game.message.proto.CommonRespProBuf.internal_static_PCommonResp_descriptor;
      }

      public com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp getDefaultInstanceForType() {
        return com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.getDefaultInstance();
      }

      public com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp build() {
        com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp buildPartial() {
        com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp result = new com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultType_ = resultType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp) {
          return mergeFrom((com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp other) {
        if (other == com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp.getDefaultInstance()) return this;
        if (other.hasResultType()) {
          setResultType(other.getResultType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultType()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doteyplay.game.message.proto.CommonRespProBuf.PCommonResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 resultType = 1;
      private int resultType_ ;
      /**
       * <code>required int32 resultType = 1;</code>
       *
       * <pre>
       *结果类型
       * </pre>
       */
      public boolean hasResultType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 resultType = 1;</code>
       *
       * <pre>
       *结果类型
       * </pre>
       */
      public int getResultType() {
        return resultType_;
      }
      /**
       * <code>required int32 resultType = 1;</code>
       *
       * <pre>
       *结果类型
       * </pre>
       */
      public Builder setResultType(int value) {
        bitField0_ |= 0x00000001;
        resultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 resultType = 1;</code>
       *
       * <pre>
       *结果类型
       * </pre>
       */
      public Builder clearResultType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultType_ = 0;
        onChanged();
        return this;
      }

      // required int32 status = 2;
      private int status_ ;
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *请求状态0成功其他是失败
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *请求状态0成功其他是失败
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *请求状态0成功其他是失败
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *请求状态0成功其他是失败
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PCommonResp)
    }

    static {
      defaultInstance = new PCommonResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PCommonResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PCommonResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PCommonResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020commonResp.proto\"1\n\013PCommonResp\022\022\n\nres" +
      "ultType\030\001 \002(\005\022\016\n\006status\030\002 \002(\005B4\n com.dot" +
      "eyplay.game.message.protoB\020CommonRespPro" +
      "Buf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PCommonResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PCommonResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PCommonResp_descriptor,
              new java.lang.String[] { "ResultType", "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
