package com.doteyplay.game.constants;

public enum ActionResultType
{
	SUCCESS,//0
	SOURCE_DEAD,//1
	SOURCE_NOT_EXIST,//2
	TARGET_ERROR,//3
	TARGET_NOT_EXIST,//4
	TARGET_UNSELECT,//5
	TARGET_DEAD,//6
	SKILL_ERROR,//7
	SKILL_NOT_EXIST,//8
	NOT_ENOUGH_MP,//9
	ACTION_TIMES_NOT_ENOUGH,//10
	SKILL_HAS_NO_TARGET,//11
	TAUNT_STATE,//12
	FLAY_STATE,
	HIDDEN_STATE,
	CANNT_SELECT_STATE,
	
	SPRITE_NUM_LIMIT,
	CARD_TYPE_ERROR,
	CARD_NOT_EXSIT,
	SKILL_CANNOT_USE,
	;
}
