// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonResp.proto

#ifndef PROTOBUF_commonResp_2eproto__INCLUDED
#define PROTOBUF_commonResp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_commonResp_2eproto();
void protobuf_AssignDesc_commonResp_2eproto();
void protobuf_ShutdownFile_commonResp_2eproto();

class PCommonResp;

// ===================================================================

class PCommonResp : public ::google::protobuf::Message {
 public:
  PCommonResp();
  virtual ~PCommonResp();

  PCommonResp(const PCommonResp& from);

  inline PCommonResp& operator=(const PCommonResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PCommonResp& default_instance();

  void Swap(PCommonResp* other);

  // implements Message ----------------------------------------------

  PCommonResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PCommonResp& from);
  void MergeFrom(const PCommonResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 resultType = 1;
  inline bool has_resulttype() const;
  inline void clear_resulttype();
  static const int kResultTypeFieldNumber = 1;
  inline ::google::protobuf::int32 resulttype() const;
  inline void set_resulttype(::google::protobuf::int32 value);

  // required int32 status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PCommonResp)
 private:
  inline void set_has_resulttype();
  inline void clear_has_resulttype();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 resulttype_;
  ::google::protobuf::int32 status_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_commonResp_2eproto();
  friend void protobuf_AssignDesc_commonResp_2eproto();
  friend void protobuf_ShutdownFile_commonResp_2eproto();

  void InitAsDefaultInstance();
  static PCommonResp* default_instance_;
};
// ===================================================================


// ===================================================================

// PCommonResp

// required int32 resultType = 1;
inline bool PCommonResp::has_resulttype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PCommonResp::set_has_resulttype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PCommonResp::clear_has_resulttype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PCommonResp::clear_resulttype() {
  resulttype_ = 0;
  clear_has_resulttype();
}
inline ::google::protobuf::int32 PCommonResp::resulttype() const {
  return resulttype_;
}
inline void PCommonResp::set_resulttype(::google::protobuf::int32 value) {
  set_has_resulttype();
  resulttype_ = value;
}

// required int32 status = 2;
inline bool PCommonResp::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PCommonResp::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PCommonResp::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PCommonResp::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 PCommonResp::status() const {
  return status_;
}
inline void PCommonResp::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_commonResp_2eproto__INCLUDED
