// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.doteyplay.game.message.proto;

public final class CommonProBuf {
  private CommonProBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonStringObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string regularStr = 1;
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    boolean hasRegularStr();
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    java.lang.String getRegularStr();
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    com.google.protobuf.ByteString
        getRegularStrBytes();

    // required int32 textId = 2;
    /**
     * <code>required int32 textId = 2;</code>
     *
     * <pre>
     *文本id
     * </pre>
     */
    boolean hasTextId();
    /**
     * <code>required int32 textId = 2;</code>
     *
     * <pre>
     *文本id
     * </pre>
     */
    int getTextId();

    // repeated string replaceList = 3;
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    java.util.List<java.lang.String>
    getReplaceListList();
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    int getReplaceListCount();
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    java.lang.String getReplaceList(int index);
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    com.google.protobuf.ByteString
        getReplaceListBytes(int index);
  }
  /**
   * Protobuf type {@code CommonStringObject}
   *
   * <pre>
   *通用文本信息对象
   * </pre>
   */
  public static final class CommonStringObject extends
      com.google.protobuf.GeneratedMessage
      implements CommonStringObjectOrBuilder {
    // Use CommonStringObject.newBuilder() to construct.
    private CommonStringObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommonStringObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommonStringObject defaultInstance;
    public static CommonStringObject getDefaultInstance() {
      return defaultInstance;
    }

    public CommonStringObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommonStringObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              regularStr_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              textId_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                replaceList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              replaceList_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          replaceList_ = new com.google.protobuf.UnmodifiableLazyStringList(replaceList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doteyplay.game.message.proto.CommonProBuf.internal_static_CommonStringObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doteyplay.game.message.proto.CommonProBuf.internal_static_CommonStringObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.class, com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.Builder.class);
    }

    public static com.google.protobuf.Parser<CommonStringObject> PARSER =
        new com.google.protobuf.AbstractParser<CommonStringObject>() {
      public CommonStringObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonStringObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommonStringObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string regularStr = 1;
    public static final int REGULARSTR_FIELD_NUMBER = 1;
    private java.lang.Object regularStr_;
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    public boolean hasRegularStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    public java.lang.String getRegularStr() {
      java.lang.Object ref = regularStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regularStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string regularStr = 1;</code>
     *
     * <pre>
     *替换标示符
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRegularStrBytes() {
      java.lang.Object ref = regularStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regularStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 textId = 2;
    public static final int TEXTID_FIELD_NUMBER = 2;
    private int textId_;
    /**
     * <code>required int32 textId = 2;</code>
     *
     * <pre>
     *文本id
     * </pre>
     */
    public boolean hasTextId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 textId = 2;</code>
     *
     * <pre>
     *文本id
     * </pre>
     */
    public int getTextId() {
      return textId_;
    }

    // repeated string replaceList = 3;
    public static final int REPLACELIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList replaceList_;
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    public java.util.List<java.lang.String>
        getReplaceListList() {
      return replaceList_;
    }
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    public int getReplaceListCount() {
      return replaceList_.size();
    }
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    public java.lang.String getReplaceList(int index) {
      return replaceList_.get(index);
    }
    /**
     * <code>repeated string replaceList = 3;</code>
     *
     * <pre>
     *替换内容列表
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReplaceListBytes(int index) {
      return replaceList_.getByteString(index);
    }

    private void initFields() {
      regularStr_ = "";
      textId_ = 0;
      replaceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRegularStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTextId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRegularStrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, textId_);
      }
      for (int i = 0; i < replaceList_.size(); i++) {
        output.writeBytes(3, replaceList_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRegularStrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, textId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < replaceList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(replaceList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getReplaceListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonStringObject}
     *
     * <pre>
     *通用文本信息对象
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doteyplay.game.message.proto.CommonProBuf.CommonStringObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doteyplay.game.message.proto.CommonProBuf.internal_static_CommonStringObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doteyplay.game.message.proto.CommonProBuf.internal_static_CommonStringObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.class, com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.Builder.class);
      }

      // Construct using com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        regularStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        textId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        replaceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doteyplay.game.message.proto.CommonProBuf.internal_static_CommonStringObject_descriptor;
      }

      public com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject getDefaultInstanceForType() {
        return com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.getDefaultInstance();
      }

      public com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject build() {
        com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject buildPartial() {
        com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject result = new com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.regularStr_ = regularStr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.textId_ = textId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          replaceList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              replaceList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.replaceList_ = replaceList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject) {
          return mergeFrom((com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject other) {
        if (other == com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject.getDefaultInstance()) return this;
        if (other.hasRegularStr()) {
          bitField0_ |= 0x00000001;
          regularStr_ = other.regularStr_;
          onChanged();
        }
        if (other.hasTextId()) {
          setTextId(other.getTextId());
        }
        if (!other.replaceList_.isEmpty()) {
          if (replaceList_.isEmpty()) {
            replaceList_ = other.replaceList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReplaceListIsMutable();
            replaceList_.addAll(other.replaceList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRegularStr()) {
          
          return false;
        }
        if (!hasTextId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doteyplay.game.message.proto.CommonProBuf.CommonStringObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string regularStr = 1;
      private java.lang.Object regularStr_ = "";
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public boolean hasRegularStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public java.lang.String getRegularStr() {
        java.lang.Object ref = regularStr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          regularStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRegularStrBytes() {
        java.lang.Object ref = regularStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regularStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public Builder setRegularStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        regularStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public Builder clearRegularStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        regularStr_ = getDefaultInstance().getRegularStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string regularStr = 1;</code>
       *
       * <pre>
       *替换标示符
       * </pre>
       */
      public Builder setRegularStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        regularStr_ = value;
        onChanged();
        return this;
      }

      // required int32 textId = 2;
      private int textId_ ;
      /**
       * <code>required int32 textId = 2;</code>
       *
       * <pre>
       *文本id
       * </pre>
       */
      public boolean hasTextId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 textId = 2;</code>
       *
       * <pre>
       *文本id
       * </pre>
       */
      public int getTextId() {
        return textId_;
      }
      /**
       * <code>required int32 textId = 2;</code>
       *
       * <pre>
       *文本id
       * </pre>
       */
      public Builder setTextId(int value) {
        bitField0_ |= 0x00000002;
        textId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 textId = 2;</code>
       *
       * <pre>
       *文本id
       * </pre>
       */
      public Builder clearTextId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        textId_ = 0;
        onChanged();
        return this;
      }

      // repeated string replaceList = 3;
      private com.google.protobuf.LazyStringList replaceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReplaceListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          replaceList_ = new com.google.protobuf.LazyStringArrayList(replaceList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public java.util.List<java.lang.String>
          getReplaceListList() {
        return java.util.Collections.unmodifiableList(replaceList_);
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public int getReplaceListCount() {
        return replaceList_.size();
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public java.lang.String getReplaceList(int index) {
        return replaceList_.get(index);
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReplaceListBytes(int index) {
        return replaceList_.getByteString(index);
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public Builder setReplaceList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceListIsMutable();
        replaceList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public Builder addReplaceList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceListIsMutable();
        replaceList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public Builder addAllReplaceList(
          java.lang.Iterable<java.lang.String> values) {
        ensureReplaceListIsMutable();
        super.addAll(values, replaceList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public Builder clearReplaceList() {
        replaceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string replaceList = 3;</code>
       *
       * <pre>
       *替换内容列表
       * </pre>
       */
      public Builder addReplaceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceListIsMutable();
        replaceList_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CommonStringObject)
    }

    static {
      defaultInstance = new CommonStringObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CommonStringObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonStringObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommonStringObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"M\n\022CommonStringObject\022\022\n\n" +
      "regularStr\030\001 \002(\t\022\016\n\006textId\030\002 \002(\005\022\023\n\013repl" +
      "aceList\030\003 \003(\tB0\n com.doteyplay.game.mess" +
      "age.protoB\014CommonProBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CommonStringObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CommonStringObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CommonStringObject_descriptor,
              new java.lang.String[] { "RegularStr", "TextId", "ReplaceList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
